### ISSUE TITLE
Vídeos

### ISSUE THREAD

**Issue by Neules** [lahoramaker/curso-objetos-conectados-nano#7]
Hey! Me está encantando el curso! pero está incompleto!! 😉  Queremos los vídeos de los módulos 4-6! 😝 

Sólo quería preguntar por ellos...hacer un poco de presión popular jeje

Un abrazo y un saludo!

**Comment by elsatch** [comment]
Gracias @Neules por el empujón. Ya están actualizados los videos y añadidos a una playlist para que sea mucho más fácil localizarlos.

Ya me contarás que te parecen 😉
